{{- if and .Values.basicAuth.create (not .Values.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kirka.fullname" . }}-basic-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kirka.labels" . | nindent 4 }}
type: Opaque
stringData:
  users.htpasswd: |
    {{- .Values.basicAuth.htpasswd | nindent 4 }}
{{- end }}
