apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kirka.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kirka.labels" . | nindent 4 }}
data:
  HBASE_ZOOKEEPER_QUORUM: {{ .Values.config.hbaseZookeeperQuorum | quote }}
  HBASE_ZOOKEEPER_PROPERTY_CLIENTPORT: {{ .Values.config.hbaseZookeeperPort | quote }}
  HADOOP_HDFS_URI: {{ .Values.config.hdfsUri | quote }}
  SECURITY_ENABLED: {{ .Values.config.securityEnabled | quote }}
  SECURITY_AUTHENTICATION_TYPE: {{ .Values.config.securityAuthType | quote }}
  SECURITY_ADMIN_USERS: {{ .Values.config.securityAdminUsers | quote }}
  SECURITY_USERS_FILE: {{ .Values.config.securityUsersFile | quote }}
  SECURITY_TRUSTED_PROXIES: {{ .Values.config.securityTrustedProxies | quote }}
  KIRKA_API_NAMING: {{ .Values.config.kirkaApiNaming | quote }}
  SECURITY_KERBEROS_ENABLED: {{ .Values.config.kerberosEnabled | quote }}
  {{- if .Values.config.kerberosPrincipal }}
  SECURITY_KERBEROS_PRINCIPAL: {{ .Values.config.kerberosPrincipal | quote }}
  {{- end }}
  {{- if .Values.config.kerberosKeytab }}
  SECURITY_KERBEROS_KEYTAB: {{ .Values.config.kerberosKeytab | quote }}
  {{- end }}
  RANGER_SERVICE_NAME: {{ .Values.config.rangerServiceName | quote }}
  RANGER_ADMIN_URL: {{ .Values.config.rangerAdminUrl | quote }}
